version: '3.7'
services:
    node:
      build: node
      hostname: node
      container_name: dev
      volumes:
        - node-v:/ws
      working_dir: /ws
  
  volumes:
    node-v:
      driver: local  